### ISSUE TITLE
Mask and parse errors both on the same input

### ISSUE THREAD

**Issue by Roqk** [angular-ui/ui-mask#156] opened 2016-05-25 14:00 UTC
Hi,
i verified that if you write a not valid text in an input with ui-mask it produce **two different errors** on it: **mask** and **parse**.

I don't understand why this directive should put both those errors and so i think this is an issue.
I think that mask error should be enough, or not? 

I've made a **[Plunker](https://embed.plnkr.co/rfOnJtJc8FlfVei5jSsC/)** to verify by yourself

thanks in advance

**Comment by lukepfeiffer10** [comment] 2016-05-25 14:27
After a little digging it appears that any `$parser` that returns `undefined` will trigger angular to add the `parse` error.

I'm checking to see if the `parser` function can be changed to not return `undefined` and still function properly.

**Comment by lukepfeiffer10** [comment] 2016-05-25 14:40
After looking into this and reading a little bit about the `$parsers` and `$validators` arrays in angular, I think this functionality is working as intended. The `parse` fails which is true for incomplete/invalid entries and so that ensures no validators are being run as those would most certainly fail as well.

**Comment by Roqk** [comment] 2016-05-25 15:41
I try to explain my situation: we are using a simple directive to list all form errors ([angular-form-errors-directive](https://github.com/CWSpear/angular-form-errors-directive)) so when we use ui-mask on an input it lists two items for the same input and for the same error so it's redundant.
Obviously we could skip one of them when we found both but we have seen that the _Angular way_ is to list just an error at time on every input.

i've made another [Plunker](https://embed.plnkr.co/brldBK8UPZGQI5JJGAjQ/) where you can verify this behavior

**Comment by lukepfeiffer10** [comment] 2016-06-06 19:10
Closing as intended functionality.

**Closed by lukepfeiffer10** 2016-06-06 19:10 UTC
