### ISSUE TITLE
Masked value should not be set if unmasked value is empty

### ISSUE THREAD

**Issue by richardkhchang** [angular-ui/ui-mask#137] opened 2016-03-21 18:23 UTC
Hi,

I'm currently trying to get google chrome auto-fill to work on a form that contains inputs that use a ui-mask. I'm running into an issue where auto-fill stops working on inputs that use ui-mask once the input has been touched.

I've investigated the issue, and this is the cause:
* auto-fill only populates fields that are empty and do not contain text
* ui-mask re-applies the mask to whatever is entered any time input is detected
* ui-mask sets the value of the input to the masked text even if the unmasked value is empty.

Here is a more detailed example of the use case:
* when I first view the page, the phone number input element has a the following attributes: [ui-mask-placeholder-char="(___) ___-____", value=""]. The mask format is visible in grey text in the input, even though there is no value, because of the place-holder.
* if I trigger auto-fill at this point, the phone number gets populated with whatever phone number is stored by the user, as expected.
* However, if I focus on phone number input element (regardless of whether or not anything is entered), the eventHandler(e) function of the ui-mask script will set the masked value. The phone number input element will end up with the following attributes: [ui-mask-placeholder-char="(___) ___-____", value="(___) ___-____"]. The mask format is visible in black text because it is actually set to that value.
* Because the value always contains text after this point regardless of what is done to it, if I trigger auto-fill at any point after this, the stored phone number never gets populated.

This seems like a bug to me, as I can't think of any valid or intentional reason that the input should not revert back to an empty value relying on place-holder text if the value entered is empty.

To temporarily manually fix this, I made the following change to the script:

function eventHandler(e) {
   .....
   .....
   // Value Handling
   // ==============
   .....
   .....
   if (valUnmasked != '')
   {
        iElement.val(valMasked);
   }
   else
   {
        iElement.val('');                                    
   }
   .....
   .....
}

With this fix applied, the phone number input element has a the following attributes: [ui-mask-placeholder-char="(___) ___-____", value=""] after any input that results in an empty value. The mask format is visible in grey text in the input, but there is no value.

Please consider making an equivalent change.

Thanks,
Richard Chang

**Comment by lukepfeiffer10** [comment] 2016-03-21 19:02
Not sure if this is the cause of the issue, although I suspect as much, but you are using the `ui-mask-placeholder-char` attribute incorrectly. I would suggest removing that attribute and trying your situation again. 

The `uiMaskPlaceholderChar` is meant to be set as a single character or the word `space` which then changes the default placeholder character, `_`, to whatever you assign it to be. This affects what is displayed when focusing the field the first time. For example, if you have a mask defined as `9999` the first time you enter the field the value in the field would be `____` with the default placeholder character.

**Closed** 2016-04-08 14:25 UTC
