### ISSUE TITLE
masked fields are filled with empty string 

### ISSUE THREAD

**Issue by salarmehr** [angular-ui/ui-mask#28] opened 2015-08-09 13:26 UTC
If a masked field which is initially null, get focused and leaved empty its values is set to empty string (''). I guess its value should be unchanged.

**Comment by Tim91084** [comment] 2015-10-27 00:26
I think this and #41 are likely the same issue

**Comment by PowerKiKi** [comment] 2015-10-27 03:11
Closing as duplicate of #41

**Closed by PowerKiKi** 2015-10-27 03:11 UTC
